# Generated by Django 3.0.2 on 2020-02-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200205_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unsolved problem'), (2, 'Solution is ongoing'), (3, 'Solved problem')], default=1),
        ),
    ]
